/*
 * Copyright (C) 2026 yangqiong
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3 of the License
 * only ("AGPL-3.0-only") and not any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.yangqiongai.ai.agent.core.trace;

import com.yangqiongai.ai.agent.core.context.AgentContext;
import com.yangqiongai.ai.agent.core.model.request.AgentRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * TraceCollector单元测试
 */
class TraceCollectorTest {

    private TraceCollector collector;

    private AgentContext context;

    @BeforeEach
    void setUp() {
        collector = new TraceCollector();
        AgentRequest request = new AgentRequest()
                .agentCode("chat")
                .sessionId("session-1")
                .input("hello")
                .userId("user-1");
        context = new AgentContext(request);
    }

    @Test
    @DisplayName("configure()设置追踪上下文")
    void configure_setsTraceContext() {
        TraceContext traceCtx = new TraceContext("trace-1", "run-1", "chat", "session-1");

        collector.configure(context, traceCtx);

        assertThat(context.getTraceId()).isEqualTo("trace-1");
        assertThat(context.getRunId()).isEqualTo("run-1");
        assertThat(context.<Object>getAttribute("traceContext")).isNotNull();
    }

    @Test
    @DisplayName("configure() null traceCtx时自动生成")
    void configure_nullTraceCtx_autoGenerated() {
        collector.configure(context, null);

        assertThat(context.getTraceId()).isNotBlank();
        assertThat(context.getRunId()).isNotBlank();
    }

    @Test
    @DisplayName("onAgent()记录Agent生命周期追踪")
    void onAgent_recordsAgentPhase() {
        collector.configure(context, null);

        collector.onAgent(context, "start");

        assertThat(context.<Object>getAttribute("lastAgentPhase")).isEqualTo("start");
        assertThat(context.<Object>getAttribute("lastAgentTime")).isNotNull();
    }

    @Test
    @DisplayName("onReasoning()记录推理步骤")
    void onReasoning_recordsReasoningStep() {
        collector.configure(context, null);

        collector.onReasoning(context, "thinking about the answer");

        assertThat(context.<Object>getAttribute("lastReasoning")).isEqualTo("thinking about the answer");
    }

    @Test
    @DisplayName("onActing()记录工具调用")
    void onActing_recordsToolCall() {
        collector.configure(context, null);

        collector.onActing(context, "searchTool", Map.of("query", "test"));

        assertThat(context.<Object>getAttribute("lastToolName")).isEqualTo("searchTool");
        assertThat(context.<Object>getAttribute("lastToolTime")).isNotNull();
    }

    @Test
    @DisplayName("onModelCall()记录模型调用")
    void onModelCall_recordsModelCall() {
        collector.configure(context, null);

        collector.onModelCall(context, "gpt-4", 150L);

        assertThat(context.<Object>getAttribute("lastModelId")).isEqualTo("gpt-4");
        assertThat(context.<Object>getAttribute("lastModelLatencyMs")).isEqualTo(150L);
    }

    @Test
    @DisplayName("onSystemPrompt()记录系统提示词注入")
    void onSystemPrompt_recordsSystemPrompt() {
        collector.configure(context, null);

        collector.onSystemPrompt(context, "You are a helpful assistant");

        assertThat(context.<Object>getAttribute("lastSystemPrompt")).isEqualTo("You are a helpful assistant");
    }

    @Test
    @DisplayName("getTraceEntries()返回追踪条目")
    void getTraceEntries_returnsTraceEntries() {
        collector.configure(context, null);
        collector.onAgent(context, "start");
        collector.onModelCall(context, "gpt-4", 100L);

        Map<String, Map<String, Object>> entries = collector.getTraceEntries(context);

        assertThat(entries).isNotEmpty();
    }

    @Test
    @DisplayName("最大100条追踪条目限制")
    void maxTraceEntries_limit() {
        collector.configure(context, null);

        // 添加超过100条追踪
        for (int i = 0; i < 110; i++) {
            collector.onAgent(context, "phase-" + i);
        }

        Map<String, Map<String, Object>> entries = collector.getTraceEntries(context);
        assertThat(entries.size()).isLessThanOrEqualTo(100);
    }

    @Test
    @DisplayName("未configure时getTraceEntries返回空Map")
    void getTraceEntries_withoutConfigure_returnsEmptyMap() {
        Map<String, Map<String, Object>> entries = collector.getTraceEntries(context);

        assertThat(entries).isEmpty();
    }
}
